
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 20 17:05:21 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 40;
  public static final int LBRACKET = 43;
  public static final int CHAR = 50;
  public static final int CONST = 10;
  public static final int SLASH = 30;
  public static final int CASE = 19;
  public static final int LOWER = 36;
  public static final int NOTEQUAL = 33;
  public static final int LPAREN = 24;
  public static final int SEMI = 23;
  public static final int CONTINUE = 18;
  public static final int LOWEREQUAL = 37;
  public static final int MINUS = 28;
  public static final int RPAREN = 25;
  public static final int OROR = 39;
  public static final int BOOL = 49;
  public static final int COMMA = 22;
  public static final int CLASS = 7;
  public static final int EQUALEQUAL = 32;
  public static final int ANDAND = 38;
  public static final int PLUS = 20;
  public static final int IF = 11;
  public static final int DOT = 42;
  public static final int HIGHEREQUAL = 35;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 41;
  public static final int RETURN = 4;
  public static final int RBRACKET = 44;
  public static final int EQUAL = 21;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PERCENT = 31;
  public static final int NUMBER = 47;
  public static final int HIGHER = 34;
  public static final int IDENT = 48;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int SWITCH = 12;
  public static final int TIMES = 29;
  public static final int COLON = 46;
  public static final int LBRACE = 26;
  public static final int ELSE = 9;
  public static final int ENUM = 8;
  public static final int READ = 16;
  public static final int WHILE = 14;
  public static final int RBRACE = 27;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int QUESTION = 45;
  public static final int PRINT = 3;
  public static final int DO = 13;
}

